name: build-and-deploy-local

on:
  push:
    branches: ['main']

jobs:
  build_push:
    runs-on: self-hosted

    env:
      REGISTRY: ccplabtxt:5000
      IMAGE_NAME: ImagenPRD
      IMAGE_TAG: ${{ github.sha }}
      DEPLOYMENT_NAME: nginx-lab
      CONTAINER_NAME: nginx

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (LOCAL)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          ${{ env.CONTAINER_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}

      - name: Verify Pods
        run: kubectl get pods -o wide
