name: Build and Deploy

on:
  push:
    branches: ['main']

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      REGISTRY: localhost:5000
      IMAGE_NAME: nginx-lab
      IMAGE_TAG: ${{ github.sha }}
      DEPLOYMENT_NAME: nginx-lab
      CONTAINER_NAME: nginx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:latest

      - name: Push image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          ${{ env.CONTAINER_NAME }}=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG

          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}

      - name: Verify Pods
        run: kubectl get pods
        
